name: Build QORMLite for Windows
on: [pull_request]
jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_TARGET: release
      
    steps:
      - name: Install Qt
        id: install
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ vars.QT_VERSION }}
          host: windows
          arch: win64_mingw
          tools: tools_mingw1310
          target: desktop
          cache: true
          dir: D:\

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure and build
        shell: bash
        run: |
          echo "Qt directory : $QT_DIR"
          echo "PATH=$QT_DIR/Tools/mingw1310_64/bin:$QT_DIR/6.10.0/mingw_64/bin:$PATH" >> $GITHUB_ENV
          echo "Path : $PATH"
          mkdir -p build
          cd build
          qmake ../QORMLiteParent.pro CONFIG+=$BUILD_TARGET
          mingw32-make -j$NUMBER_OF_PROCESSORS

      #- name: Run tests
       # shell: bash
       # run: |
       #   cd build/test/$BUILD_TARGET
       #   for test in *.exe; do
       #     echo "Running $test..."
       #     "$PWD/$test"
       #   done
      