name: QORM Build
on: [push, pull_request]
jobs:
  install-qt:
    uses: jurplel/install-qt-action@v4
    with:
        version: '6.10.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
