name: Setup Qt

on:
  workflow_call:
    inputs:
      qt_version:
        required: true
        type: string
    outputs:
      qt_root:
        description: "Path to installed Qt"
        value: ${{ jobs.setup.outputs.qt_root }}

jobs:
  setup:
    runs-on: windows-latest
    outputs:
      qt_root: ${{ steps.export.outputs.qt_root }}
    steps:
      - name: Install Qt
        id: install
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ inputs.qt_version }}
          host: windows
          arch: win64_mingw
          tools: tools_mingw1310
          target: desktop
          cache: true
          dir: D:\
      - name: Export Qt root dir
        id: export
        shell: bash
        run: |
          echo "QT_ROOT_DIR: $QT_ROOT_DIR"
          QT_UNIX_ROOT_DIR=$(cygpath -u "$(dirname "$QT_ROOT_DIR")")
          echo "QT_UNIX_ROOT_DIR: $QT_UNIX_ROOT_DIR"
          echo "qt_root=${QT_UNIX_ROOT_DIR}" >> $GITHUB_OUTPUT