name: Setup Qt

on:
  workflow_call:
    outputs:
      qt_root:
        description: "Path to installed Qt"
        value: ${{ jobs.setup.outputs.qt_root }}

jobs:
  setup:
    runs-on: windows-latest
    outputs:
      qt_root: ${{ steps.install.outputs.qt_root_dir }}
    env:
      QT_BUILD_VERSION: 6.10.0
      BUILD_TARGET: release
    steps:
      - name: Install Qt
        id: install
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_BUILD_VERSION }}
          host: windows
          arch: win64_mingw
          tools: tools_mingw1310
          target: desktop
          cache: true